SELECT
	*
FROM
	(
		SELECT
			M.TWEET_ID,
			CREATED_AT::DATE,
			AGGRESSOR,
			TARGET,
			ACTION,
			ST_MAKELINE (AGGRESSOR_GEOM, TARGET_GEOM) AS GEOM
		FROM
			MILITARY_ACTIONS M
			LEFT JOIN TWEETS T ON T.TWEET_ID = M.TWEET_ID
		WHERE
			AGGRESSOR = 'United States of America'
	)
WHERE
	GEOM IS NOT NULL