DROP MATERIALIZED VIEW IF EXISTS TENSION_INDEX_MV;

CREATE MATERIALIZED VIEW TENSION_INDEX_MV AS
WITH
	RAW AS (
		SELECT
			WA.ENTITY_NAME AS COUNTRY,
			T.TWEET_ID,
			T.SUMMARY_TEXT,
			T.CREATED_AT,
			T.CONFLICT_TYPOLOGY,
			T.IMPORTANCE_SCORE,
			T.TWEET_URL,
			T.USERNAME,
			T.LOCATION_NAME,
			T.LOCATION_ACCURACY,
			ST_X (ST_CENTROID (T.GEOM)) AS LONGITUDE,
			ST_Y (ST_CENTROID (T.GEOM)) AS LATITUDE,
			(
				CASE
					WHEN T.CONFLICT_TYPOLOGY = 'MIL' THEN POWER(T.IMPORTANCE_SCORE, 1.6) * 2.0
					WHEN T.CONFLICT_TYPOLOGY = 'MOVE' THEN POWER(T.IMPORTANCE_SCORE, 1.3) * 0.8
					WHEN T.CONFLICT_TYPOLOGY = 'POL' THEN POWER(T.IMPORTANCE_SCORE, 1.1) * 0.4
					ELSE T.IMPORTANCE_SCORE * 0.2
				END
			) * EXP(
				-0.15 * (
					EXTRACT(
						EPOCH
						FROM
							(NOW() - T.CREATED_AT)
					) / 86400
				)
			) AS EVENT_SCORE
		FROM
			TWEETS T
			JOIN WORLD_AREAS WA ON ST_INTERSECTS (T.GEOM, WA.GEOM)
		WHERE
			T.CREATED_AT >= NOW() - INTERVAL '7 days'
			AND T.IMPORTANCE_SCORE IS NOT NULL
	),
	COUNTRY_TOTALS AS (
		SELECT
			COUNTRY,
			SUM(EVENT_SCORE) AS RAW_SCORE,
			-- Score logarithmique : compresse les extrêmes, préserve le classement
			LN(1 + SUM(EVENT_SCORE)) AS LOG_SCORE
		FROM
			RAW
		GROUP BY
			COUNTRY
	),
	DISTRIB AS (
		SELECT
			PERCENTILE_CONT(0.25) WITHIN GROUP (
				ORDER BY
					LOG_SCORE
			) AS P25,
			PERCENTILE_CONT(0.50) WITHIN GROUP (
				ORDER BY
					LOG_SCORE
			) AS P50,
			PERCENTILE_CONT(0.75) WITHIN GROUP (
				ORDER BY
					LOG_SCORE
			) AS P75,
			PERCENTILE_CONT(0.95) WITHIN GROUP (
				ORDER BY
					LOG_SCORE
			) AS P95,
			PERCENTILE_CONT(0.98) WITHIN GROUP (
				ORDER BY
					LOG_SCORE
			) AS P98,
			PERCENTILE_CONT(0.99) WITHIN GROUP (
				ORDER BY
					LOG_SCORE
			) AS P99
		FROM
			COUNTRY_TOTALS
	)
SELECT
	CT.COUNTRY,
	ROUND(
		LEAST(
			100,
			((CT.LOG_SCORE / NULLIF(D.P99, 0)) * 100)::NUMERIC
		),
		0
	) AS TENSION_SCORE,
	CASE
		WHEN CT.LOG_SCORE >= D.P95 THEN 'Open Warfare'
		WHEN CT.LOG_SCORE >= D.P75 THEN 'High Strategic Tension'
		WHEN CT.LOG_SCORE >= D.P50 THEN 'Significant Tension'
		WHEN CT.LOG_SCORE >= D.P25 THEN 'Moderate Tension'
		ELSE 'Low Tension / Stable'
	END AS TENSION_LEVEL,
	JSON_AGG(
		JSON_BUILD_OBJECT(
			'date',
			R.CREATED_AT::DATE,
			'importance_score',
			R.IMPORTANCE_SCORE,
			'conflict_typology',
			R.CONFLICT_TYPOLOGY,
			'score_contribution_normalized',
			ROUND(
				(
					(R.EVENT_SCORE / NULLIF(CT.RAW_SCORE, 0)) * LEAST(100, ((CT.LOG_SCORE / NULLIF(D.P99, 0)) * 100))
				)::NUMERIC,
				2
			),
			'SUMMARY_TEXT',
			LEFT(R.SUMMARY_TEXT, 200),
			'location_name',
			R.LOCATION_NAME,
			'location_accuracy',
			R.LOCATION_ACCURACY,
			'longitude',
			R.LONGITUDE,
			'latitude',
			R.LATITUDE
		)
		ORDER BY
			R.CREATED_AT DESC
	) AS EVENEMENTS
FROM
	COUNTRY_TOTALS CT
	CROSS JOIN DISTRIB D
	LEFT JOIN RAW R ON R.COUNTRY = CT.COUNTRY
GROUP BY
	CT.COUNTRY,
	CT.RAW_SCORE,
	CT.LOG_SCORE,
	D.P25,
	D.P50,
	D.P75,
	D.P95,
	D.P98,
	D.P99
ORDER BY
	TENSION_SCORE DESC;

CREATE INDEX IDX_TENSION_COUNTRY ON TENSION_INDEX_MV (COUNTRY);

CREATE INDEX IDX_TENSION_SCORE ON TENSION_INDEX_MV (TENSION_SCORE DESC);

SELECT
	*
FROM
	TENSION_INDEX_MV;